version: '3'

services:
  redis:
    image: redis
    ports:
     - '6379:6379'
  web:
    build: .
    env_file: docker/production/.env
    command: python3 django_skeleton/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    env_file: docker/production/.env
    command: celery worker --app=django_skeleton.django_skeleton.celery.app -B
    links:
      - redis