# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 02:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('email', models.BooleanField(default=False)),
                ('email_address', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250, null=True), size=None)),
                ('email_subject', models.CharField(max_length=250, null=True)),
                ('email_message', models.TextField()),
                ('email_send', models.BooleanField(default=False)),
                ('email_has_error', models.BooleanField(default=False)),
                ('email_response', models.TextField()),
                ('email_error', models.TextField()),
                ('sms', models.BooleanField(default=False)),
                ('mobile_number', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), size=None)),
                ('sms_subject', models.CharField(max_length=250, null=True)),
                ('sms_message', models.TextField()),
                ('sms_send', models.BooleanField(default=False)),
                ('sms_has_error', models.BooleanField(default=False)),
                ('sms_response', models.TextField()),
                ('sms_error', models.TextField()),
            ],
        ),
    ]
