# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 12:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180107_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
