# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 06:00
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(upload_to='OCR/images/')),
                ('result', models.TextField()),
                ('working_path', models.TextField()),
                ('log', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='ocr_request_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='ocr_request_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
