# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 01:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_invoiced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='log',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
