# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20171122_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='billing/tickets')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='billing.Ticket')),
            ],
        ),
        migrations.DeleteModel(
            name='TicketsImage',
        ),
    ]
