# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 01:05
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20171122_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='log',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=[], size=None),
        ),
    ]
