# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_by_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_by_sms',
            field=models.BooleanField(default=False),
        ),
    ]
