# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 21:01
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Company name')),
                ('rfc', models.CharField(help_text='Use the following format XXX[X]999999XXX', max_length=13, unique=True, verbose_name='Tax ID')),
                ('address', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('collaborators', models.ManyToManyField(related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Collaborators')),
            ],
            options={
                'ordering': ['rfc'],
            },
        ),
    ]
