# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-09 06:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_swipper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mines',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(1, 'Started'), (2, 'Paused'), (3, 'Lost'), (4, 'Won')], default=1),
        ),
    ]
