# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-09 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine_swipper', '0003_auto_20180509_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='payers',
            new_name='players',
        ),
    ]
