# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-09 07:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_swipper', '0005_auto_20180509_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cells',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='game',
            name='flags',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), null=True, size=None),
        ),
    ]
