# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-09 17:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_swipper', '0006_auto_20180509_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='flags',
        ),
        migrations.AddField(
            model_name='game',
            name='revelead_cells',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), null=True, size=None),
        ),
    ]
