# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 04:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_swipper', '0009_game_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='queue',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
